### PR TITLE
suggested style changes

### PR DESCRIPTION
**Pull request by maxstarkenburg**
As discussed in e-mail. My apologies if I was supposed to commit to a branch and/or commit in small chunks. I can redo with smaller commits that explain things, if that's helpful. I did try running precompile.sh, but got an error. These changes don't take into account behind-the-login or forum views, so I'm not sure if things will break there.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
I like the design, especially the search results view. Here are some suggestions. Feel free to push back if you think the suggestions don't make sense.

- Whenever there is significant text on the gray background, it doesn't look so good. Please take a look at the home page and the help pages. I think it may be better to just put the entire content in the white box.
- Similarly, the name/description on the script pages aren't so great on the gray background.
- It may be better to have a hover state on the UI-y links, like the right side of the search results and the top links of the script page.
- If possible, figure out to get the forum running and apply the style there. If you can't, maybe just create a user style/script and then I can merge it together.

**Comment by maxstarkenburg** [comment]
I tried addressing some of the concerns by inverting the white and gray (I also tried white on white, but it just looked kinda odd). I think that works ok, but I think the gray background doesn't look so odd for help/home either; I suspect it might just take some getting used to (like walking into a slightly darker room)? I didn't think boxing everything up on all pages would look good either, but admittedly didn't try it. I also tried putting the script title inside the box on script pages. I think it looks decent, but slightly messes up the hierarchy w/ the links above. Anyway, what do you think?

screenshot from 2016-10-17 16-19-04
screenshot from 2016-10-17 16-25-03

Re: a hover state on the right/top links, I agree that that would be fine. Did you mean using my style as the hover state instead of as a "current" link look? I was hoping to really emphasize the "current" link look since that's one thing that I feel gets lots in the current design.

**Comment by JasonBarnabe** [comment]
I prefer how it was before, with the gray on the outside. It's OK to go like that; it can always be tweaked after.

Having the script title under the "tabs" looks OK to me.

I like your "current" link look as well. Something more subtle for hover would be good.

**Comment by maxstarkenburg** [comment]
Forgot to work on the forum. Am traveling tomorrow so it'll have to wait a bit.

**Comment by leoncastro** [comment]
I made a userscript based on this style, but with some little changes. You can find the source code [here](https://greasyfork.org/scripts/24423-greasyfork-theme).
I also made a promotional thread in the Greasy Fork Forum, [here](https://greasyfork.org/en/forum/discussion/12384/greasyfork-theme), to get feedbacks of those who don't have a GitHub account.

**Comment by JasonBarnabe** [comment]
I am going to take this as is an apply the style to the forum before putting it live. After that we can tweak things. Thanks again for your efforts @maxstarkenburg.

**Pull request merged**
