### PR TITLE
Mobile friendly css r2

### PR DESCRIPTION
**Pull request by strongop**
Move CSS setting to function-specific files.

- Fixed user name overlap with site name.
- Fixed Script for cut off.

Use smaller padding for main text elements.

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
As previously mentioned, please retain some padding at low widths. Putting 4px left and right padding on width-constraint looks good to me, but you may have a better way.

**Comment by strongop** [comment]
Sorry, misunderstood what you say.
I've set the padding to 1.2% of view port width, that's about 4px for 440px-viewport, and 11px for 960px-viewport.

**Comment by strongop** [comment]
Sorry, misunderstood what you say.

**Comment by JasonBarnabe** [comment]
Awesome, thanks!

**Pull request merged**
