### PR TITLE
Clarified each section.

### PR DESCRIPTION
**Pull request by knoajp**
It's just one of the ideas.
(I guess I've proposed this a few days ago, but I can't find the log of it, so I retry it. I'm sorry if it to be duplicated)

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
I don't like this - it's too whitespace-y. It's confusing if there a multiple antifeatures.

In the future it would be better if you explained what problem you're trying to solve and include screenshots.

**Comment by knoajp** [comment]
Okay, I understand.

I want to improve readability to make users actually read the notation, without ignoring the entire text block like "terms of service".

I think the long text block without breaking lines tends to be ignored too, as well as whitespace-y blocks. And I simply prefer the whitespace-y one.

Actually, I wanted to add some style as well, but I hesitated, or I left it to your style policy.

If you agree that clarifying each section improves readability and you simply don't like whitespace-y visual, I propose this screenshot. It has .5em top and bottom margins on paragraphs instead of 1em default and subtle background color and .5em padding on the quote.

It's also just one of the ideas and you can refuse it freely. 😉

**Comment by knoajp** [comment]
Oh, I forgot the multiple antifeatures issue.
If you approve the direction, I'll make some list styled solution later.

**Comment by JasonBarnabe** [comment]
I don't think there's any problem with how things are. If the author gives a very long explanation, it's going to be a big block of text no matter what.

**Pull request closed without merging**
