### PR TITLE
Add badge

### PR DESCRIPTION
**Pull request by adamlui**
I made a badge to promote installing one of my scripts from Greasy Fork, thought to share for anyone to use or edit

image

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
Not really interested in this, but you and anyone else is free to use it.

**Comment by adamlui** [comment]
@JasonBarnabe well if you agree other should use to drive traffic to gf, why not include it as a mere asset in repo for discovery and nothing else?

**Comment by JasonBarnabe** [comment]
I don't agree that others should use it; I'm saying others can use it if they want. I just don't want to officially suggest or support it.

**Comment by adamlui** [comment]
@JasonBarnabe oh you don't like the use of "Available on" badges, or just this one (and if so why)

Also I wasn't asking for your permission for me or others to use (but if you would've said don't use it which would have been strange to me so since it drives traffic thus increasing your afsens

**Pull request closed without merging**
