### PR TITLE
Various Chinese Translation Fixes + Some Description Fixes / Update

### PR DESCRIPTION
**Pull request by cyfung1031**
A. Content Update:

1. Added [Stay](https://apps.apple.com/app/id1591620171) as one of the examples of UserScript managers used in iOS (Safari)

2. modified english descriptions for anti-feature and webhook

2. Aligned the latest translation entries between Simplified Chinese and Traditional Chinese

B. Chinese Words for Specific Terms

1. Translation of "Moderator": Changed "管理员" into "审核员" to address the meaning difference between "Moderator" and "Administrator".

2. Translation of "Anti-feature": Replaced "可能不受欢迎的功能" to "反面特徴"
        - Anti = 反、抗、防； anti-corruption = 反貪 (action)； antibiotics = 抗生素 (material)；anti-aging = 防衰老 (process)
        - Anti- (adjective) = 反～、対～、抗～、非～、不～、～防止の◆反対・敵対・対抗・排斥を表す。 "anti-pattern" => "反面模式"

C. Localization for Traditional Chinese (zh-TW)

1. Improved the translation quality of some words used differently in Simplified Chinese and Traditional Chinese. (e.g. 會話 -> 對話)

2. localization ("code") for zh-TW - change "代碼" to "程式碼" (except country code, coupon code, etc)

3. localization ("user") for zh-TW - change "用戶" to "使用者"

4. localization ("forum") for zh-TW - Aligned forum as "討論區" instead of "論壇"
        - In Greasy Fork, the discuss forum is small scale without many sub-forum, therefore, it should be "討論區" instead of "論壇".
        - Note: In Simplified Chinese, "论坛" is always preferred.

D. Fixed some HTML formatting issues. (like missing `</li>`)

E. Added more translation entries

Incorporate & Merge #1155
Incorporate & Merge #1154

### CODE REVIEW

**Comment by JasonBarnabe** [comment]
I suggest making translation changes on https://app.transifex.com/greasy-fork/greasy-fork/dashboard/ to avoid conflicts like you have now.

Also, better to have separate PRs for separate fixes.

**Comment by cyfung1031** [comment]
> I suggest making translation changes on https://app.transifex.com/greasy-fork/greasy-fork/dashboard/ to avoid conflicts like you have now.
> 
> Also, better to have separate PRs for separate fixes.

Just keep this PR as a history record and one day I might do it in transifex :)

**Comment by cyfung1031** [comment]
Screen Shot 2023-09-25 at 22 05 33
@JasonBarnabe If I would like to add the new userscript manager to the example desciption, should I add in github and submit the PR? or all changes under config/locales/ shall only submit in transifex?

**Comment by JasonBarnabe** [comment]
Submit a PR changing it only in the English version. You may want to ask first because I get a fair number of requests to add browsers and don't necessarily want just anything in there.

**Pull request closed without merging**
